In [1]:
import torch

In [2]:
torch.__version__

'2.0.1+cu118'

## Creating Tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

To get the numbe inside the object


In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([2,4])
vector

tensor([2, 4])

In [10]:
print('vector.ndim : ',vector.ndim, 'it gives me the dimension of the tensor: 0 scalar, 1 vector, 2 matrix, ...')
print('vector.shape: ', vector.shape, 'it tells me about how the elements of the tensor are organized')

vector.ndim :  1 it gives me the dimension of the tensor: 0 scalar, 1 vector, 2 matrix, ...
vector.shape:  torch.Size([2]) it tells me about how the elements of the tensor are organized


In [11]:
matrix = torch.tensor([ [1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

**You can continue with this idea and create a tensor of any dimension**

Random tensors

In [13]:
rand_tensor = torch.rand((3,4))
rand_tensor

tensor([[0.9151, 0.1154, 0.9723, 0.7731],
        [0.1327, 0.8485, 0.1832, 0.2649],
        [0.3733, 0.4504, 0.3343, 0.2147]])

Tensor of zeros and ones

In [14]:
zeros_tensor = torch.zeros((4,4))
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones_tensor = torch.ones((2,3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Creating a range tensor

In [17]:
range_tensor = torch.arange(0,10,2)
range_tensor

tensor([0, 2, 4, 6, 8])

You can use the shape of another tensor to create a tensor of zeros or ones with the same shape

In [18]:
tensor_alike = torch.zeros_like(range_tensor)
tensor_alike

tensor([0, 0, 0, 0, 0])

In [19]:
tensor_alike_ones = torch.ones_like(range_tensor)
tensor_alike_ones

tensor([1, 1, 1, 1, 1])

**Creating tensors with defined datatype**

In [20]:
float_32_tensor = torch.tensor([1,2,3],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type,  what device is the tensor stored on? (usually GPU or CPU)
                               requires_grad=False) # if True, operations  performed on the tensor are recorded

#### PyTorch tensors & NumPy

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:




*   torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
*   torch.Tensor.numpy() - PyTorch tensor -> NumPy array.




In [21]:
import numpy as np

In [22]:
array = np.arange(0,20,4)
tensor = torch.from_numpy(array)

array, tensor

(array([ 0,  4,  8, 12, 16]), tensor([ 0,  4,  8, 12, 16]))